// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/water-billing/GoldNavy.tsx": () => import("../components/mockups/water-billing/GoldNavy.tsx"),
  "./components/mockups/water-billing/MidnightDark.tsx": () => import("../components/mockups/water-billing/MidnightDark.tsx"),
  "./components/mockups/water-billing/SlateClean.tsx": () => import("../components/mockups/water-billing/SlateClean.tsx")
};
